### ISSUE TITLE
What is left for version 1.0 ?

### ISSUE THREAD

**Issue by rcaneill** [DocOtak/gsw-xarray#56]
I created a new milestone for version 1.0.0
If I summarize the initial goals of gsw-xarray, it seems to me that if all issues left in ![milestone version 1.0.0](https://github.com/DocOtak/gsw-xarray/milestone/6) are closed, we'll have reached the goals:
* [x] Have a simple (working) version that adds cf attributes when possible
* [x] Have it work with reference pressure when needed
* [x] Add pint support
* [ ] Have an accessor (PR #53 )
* [ ] Auto-discovery of calculable quantities (issue #30)

As minor point we can add:
* [ ] Good documentation and contributor's guide (issue #10)
